spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/busbus?serverTimezone=UTC
    username: root
    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#  mvc:
#    view:
#      prefix: classpath:/templates/
#      suffix: .html
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  jpa.properties:
    hibernate.packagesToScan: com.oparin.busbus.models
    hibernate.jdbc.time_zone: Europe/Moscow
    hibernate.show_sql: true

